### PR TITLE
fixed for python 3 and prepared for pypi

### PR DESCRIPTION
**Pull request by jznf**

### CODE REVIEW

**Comment by shamrin** [comment]
Thank you @jznf! I thought it's easier for people to just copy the module into their repositories. But it looks like I was wrong.

Do you want to maintain the pypi package yourself? I can maintain it myself if you give me the `namesgenerator` package ownership. I think it's better when the repository owner and package owner is the same person - less lag between the repo changes and package update.

**Comment by shamrin** [comment]
In the meantime I've added you as a collaborator to this repository.

**Comment by jznf** [comment]
You got owner role on PyPi assigned now.

I would be pleased to help maintaining this repo/package. I use it all the time and I guess I'm not alone. And it's not much work;)

What I would do is merging the changes and deleting the fork to avoid a confusion and duplicity.

...and releasing it again with a proper meta informations (repo url, owner, maintainer, whatever).

Cheers!

**Comment by shamrin** [comment]
Thank you! I've made the changes in PR #6.

**Pull request merged**
